const {chromium}=require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
const BASE='http://127.0.0.1:4173/';const out=process.env.IVC_EVIDENCE_RUN||'initial';
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const results=[];const allErrors=[];
async function run(name,fn){const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();p.setDefaultTimeout(6500);p.on('pageerror',e=>allErrors.push(e.message));p.on('dialog',d=>d.accept());try{await p.goto(BASE);await fn(p,c);results.push({name,status:'Pass'});console.log('PASS '+name);}catch(e){results.push({name,status:'Fail',error:e.message});console.log('FAIL '+name+': '+e.message);await p.screenshot({path:'evidence/'+out+'-failure-'+results.length+'.png',fullPage:true});}await c.close();}
const click=(p,a)=>p.locator(`[data-action="${a}"]`).first().click();
const login=async(p,index='0')=>{await p.locator('select[name="account"]').selectOption(index);await p.locator('[data-form="login"] button').click();};
const state=async p=>p.evaluate(()=>JSON.parse(localStorage.getItem('ivc26-demo-v1')));
const scenario=async(p,phone)=>{await p.locator(`[data-phone="${phone}"]`).click();await p.locator('.person-result').first().waitFor();};
const selectPeople=async p=>{const boxes=p.locator('[data-person]');const ids=await boxes.evaluateAll(els=>els.map(el=>el.dataset.person));for(const id of ids)await p.locator(`[data-person="${id}"]`).check();await click(p,'begin');};
const size=async(p,value='Adult M')=>{await p.locator('select[name="size"]').selectOption(value);};
const detailsNext=async p=>p.locator('[data-form="details"] button[type="submit"]').click();
const cash=async(p,amount)=>{await click(p,'to-cash');if(amount!==undefined)await p.locator('[data-form="cash"] input[name="cash"]').fill(String(amount));await p.locator('[data-form="cash"] button[type="submit"]').click();await p.locator('.confirmation-card').first().waitFor();};
const adult=async(p,phone,amount)=>{await scenario(p,phone);await selectPeople(p);await size(p);await detailsNext(p);await cash(p,amount);};
const next=async p=>{await click(p,'next-registration');};
const demo=async(p,{date='2026-11-07',role='0',jk='Dallas HQ'}={})=>{await click(p,'demo-controls');await p.locator('select[name="demoDate"]').selectOption(date);await p.locator('select[name="account"]').selectOption(role);await p.locator('select[name="jk"]').selectOption(jk);await p.locator('[data-form="demo"] button[type="submit"]').click();};
async function eligibility(p,id,kind){await p.locator(`[data-action="eligibility"][data-id="${id}"][data-kind="${kind}"]`).click();if(kind==='coc')await p.locator('input[name="verified"]').check();else{await p.locator('input[name="facilitator"]').fill('Demo Facilitator');await p.locator('input[name="facilitatorPhone"]').fill('2145550197');}await p.locator('[data-form="eligibility"] button[type="submit"]').click();}
await run('1. Approved access, adult, no COC, inactive and no-match recovery',async(p)=>{
 await login(p,'3');assert.match(await p.locator('body').innerText(),/isn’t approved/);await login(p);
 await adult(p,'2145550101');let s=await state(p);assert.equal(s.registrations.at(-1).payment,'Paid');assert.equal(s.registrations.at(-1).fee,15);assert.equal(await p.locator('.small-qr svg').count(),1);await next(p);
 await scenario(p,'2145550106');await p.locator('[data-person]').check();await click(p,'begin');assert.match(await p.locator('[role="alert"]').innerText(),/Resolve COC/);await eligibility(p,'p-coc','coc');await click(p,'begin');await size(p);await detailsNext(p);await cash(p);s=await state(p);assert.ok(s.logs.some(l=>l.type==='COC completed at desk'&&l.jk==='Dallas HQ'&&l.time));await next(p);
 await scenario(p,'2145550107');await eligibility(p,'p-inactive','active');await selectPeople(p);await size(p);await detailsNext(p);await cash(p);assert.ok((await state(p)).logs.some(l=>l.type==='Facilitator confirmation'&&l.detail.includes('Demo Facilitator')));await next(p);
 await p.locator('input[name="phone"]').fill('123');await p.locator('[data-form="search"] button').click();assert.match(await p.locator('[role="alert"]').innerText(),/10-digit/);
 await p.locator('[data-phone="2145550190"]').click();await p.getByRole('heading',{name:/No one found/}).waitFor();await click(p,'add-person');await p.locator('input[name="name"]').fill('Demo New Volunteer');await p.locator('[data-form="add-person"] button[type="submit"]').click();const manual=await p.locator('[data-person]').getAttribute('data-person');await click(p,'begin');assert.match(await p.locator('[role="alert"]').innerText(),/Resolve COC/);await eligibility(p,manual,'active');await eligibility(p,manual,'coc');await click(p,'begin');await size(p);await detailsNext(p);await cash(p);await next(p);await p.reload();await p.locator('input[name="phone"]').fill('2145550190');await p.locator('[data-form="search"] button').click();await p.getByRole('button',{name:'Open registration',exact:true}).waitFor();assert.equal(await p.locator('[data-person]').count(),0);
 await p.screenshot({path:`evidence/${out}-eligibility-recovery.png`,fullPage:true});
});
await run('2. Guardian plus two children, typed/drawn waivers and separate tickets',async(p)=>{
 await login(p);await scenario(p,'2145550102');await selectPeople(p);await size(p,'Adult L');await detailsNext(p);await size(p,'Youth L');await p.locator('select[name="guardianId"]').selectOption('p-guardian');await detailsNext(p);await size(p,'Youth M');await p.locator('select[name="guardianId"]').selectOption('p-guardian');await detailsNext(p);
 const ids=await p.locator('[data-action="sign-child"]').evaluateAll(els=>els.map(e=>e.dataset.id));for(const [i,id]of ids.entries()){await p.locator(`[data-action="sign-child"][data-id="${id}"]`).click();await p.locator('#dialog input[name="parentName"]').fill('Samir Mitha');if(i===0){await p.locator('#dialog input[name="signature"]').fill('Samir Mitha');}else{await click(p,'signature-draw');const box=await p.locator('canvas').boundingBox();await p.mouse.move(box.x+30,box.y+90);await p.mouse.down();await p.mouse.move(box.x+80,box.y+40,{steps:5});await p.mouse.move(box.x+120,box.y+80,{steps:5});await p.mouse.move(box.x+170,box.y+50,{steps:5});await p.mouse.up();}await p.locator('#dialog input[name="consent"]').check();await p.locator('[data-form="child-sign"] button[type="submit"]').click();}
 await cash(p,45);const rows=(await state(p)).registrations.slice(-3);assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r.id)).size,3);assert.equal(rows.filter(r=>r.guardianId===rows[0].id).length,2);assert.equal(await p.locator('.small-qr svg').count(),3);await p.screenshot({path:`evidence/${out}-family-confirmation.png`,fullPage:true});
 await p.locator('[data-action="open-ticket"]').first().click();await p.locator('.ticket-qr svg').waitFor();assert.equal(await p.locator('.ticket-qr svg').count(),1);await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`evidence/${out}-guardian-ticket-mobile.png`,fullPage:true});await p.locator('.ticket-qr .qr').screenshot({path:'evidence/ticket-qr.png'});fs.writeFileSync('evidence/ticket-qr-url.txt',p.url());
});
await run('3. Teen waiting on parent, mobile signature and same-browser desk update',async(p,c)=>{
 await login(p);await scenario(p,'2145550103');await selectPeople(p);await size(p,'Adult S');await detailsNext(p);await click(p,'parent-away');await p.locator('input[name="parentName"]').fill('Demo Parent');await p.locator('input[name="parentPhone"]').fill('2145550199');await p.locator('[data-form="parent-away"] button[type="submit"]').click();await cash(p,15);assert.equal(await p.locator('.small-qr svg').count(),0);await click(p,'parent-link');const href=await p.getByRole('link',{name:/Open parent page/}).getAttribute('href');const mobile=await c.newPage();mobile.setDefaultTimeout(6500);await mobile.setViewportSize({width:390,height:844});await mobile.goto(href);await mobile.screenshot({path:`evidence/${out}-parent-mobile-before.png`,fullPage:true});await mobile.locator('input[name="parentName"]').fill('Demo Parent');await mobile.locator('input[name="signature"]').fill('Demo Parent');await mobile.locator('input[name="consent"]').check();await mobile.locator('[data-form="parent"] button[type="submit"]').click();await mobile.getByRole('heading',{name:'Parent waiver signed'}).waitFor();await p.locator('.small-qr svg').waitFor();assert.equal((await state(p)).registrations.at(-1).waiver,'Signed');await mobile.locator('[data-action="open-ticket"]').click();await mobile.locator('.ticket-qr svg').waitFor();assert.equal(await mobile.locator('.ticket-qr svg').count(),1);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.screenshot({path:`evidence/${out}-teen-ticket-mobile.png`,fullPage:true});
});
await run('4. Price switch, donations, coverage, pending payment, reports and cash close',async(p)=>{
 await login(p);await demo(p);await adult(p,'2145550105',100);let s=await state(p);assert.equal(s.transactions.at(-1).donation,80);assert.equal(s.registrations.at(-1).fee,20);await next(p);
 await scenario(p,'2145550104');await selectPeople(p);await size(p);await detailsNext(p);await click(p,'to-cash');await p.locator('[data-payment]').selectOption('Covered');await p.locator('[data-form="cash"] button[type="submit"]').click();assert.match(await p.locator('.form-error').innerText(),/Approve coverage/);await p.locator('[data-coverage]').check();await p.locator('[data-form="cash"] button[type="submit"]').click();await p.locator('.confirmation-card').waitFor();await click(p,'open-ticket');assert.ok(!(await p.locator('main').innerText()).match(/Covered|affordability/i));assert.ok(!Buffer.from(p.url().split('/').at(-1),'base64').toString().includes('Covered'));await p.goto(BASE+'#desk');await next(p);
 await scenario(p,'2145550108');await selectPeople(p);await size(p);await detailsNext(p);await click(p,'to-cash');assert.equal(await p.locator('[data-payment]').inputValue(),'Covered');await p.locator('[data-coverage]').check();await p.locator('[data-form="cash"] button[type="submit"]').click();await p.locator('.confirmation-card').waitFor();await next(p);
 await demo(p,{date:'2026-11-06'});await scenario(p,'2145550101');await selectPeople(p);await size(p);await detailsNext(p);await click(p,'to-cash');await p.locator('[data-payment]').selectOption('Pending');await p.locator('[data-form="cash"] button[type="submit"]').click();await p.locator('.confirmation-card').waitFor();const pending=(await state(p)).registrations.at(-1);await next(p);await demo(p,{date:'2026-11-07'});await p.goto(BASE+'#registrations');await p.locator(`#list-search`).fill('Amina Noor');await p.locator('[data-action="record"]').click();await click(p,'collect');await p.locator('#dialog input[name="cash"]').fill('20');await p.locator('[data-form="collect"] button[type="submit"]').click();s=await state(p);assert.equal(s.transactions.at(-1).ticketAmount,15);assert.equal(s.transactions.at(-1).donation,5);assert.equal(s.transactions.at(-1).date,'2026-11-07');await click(p,'close-dialog');
 await p.goto(BASE+'#reports');await p.getByRole('heading',{name:'The day, accounted for.'}).waitFor();await p.screenshot({path:`evidence/${out}-reports.png`,fullPage:true});const download=p.waitForEvent('download');await click(p,'export-csv');const dl=await download;assert.match(dl.suggestedFilename(),/csv$/);
 await p.goto(BASE+'#close');s=await state(p);const expected=s.transactions.filter(t=>t.date==='2026-11-07'&&t.jk==='Dallas HQ').reduce((n,t)=>n+t.amount,0);await p.locator('input[name="counted"]').fill(String(expected-1));await p.locator('input[name="handedTo"]').fill('Demo Treasurer');await p.locator('[data-form="close"] button[type="submit"]').click();assert.match(await p.locator('.form-error').innerText(),/Explain the difference/);await p.locator('textarea[name="note"]').fill('Demo count is one dollar short; recorded for reconciliation.');await p.locator('[data-form="close"] button[type="submit"]').click();assert.equal((await state(p)).closes.at(-1).variance,-1);await p.screenshot({path:`evidence/${out}-cash-close.png`,fullPage:true});
 await p.goto(BASE+'#desk');await demo(p,{role:'1',jk:'Denver'});await p.goto(BASE+'#registrations');await p.locator('#list-search').fill('');assert.ok(!(await p.locator('tbody').innerText()).includes('Amina Noor'));await p.goto(BASE+'#reports');assert.match(await p.locator('main').innerText(),/needs an admin account/);await p.goto(BASE+'#close');assert.match(await p.locator('main').innerText(),/needs an admin account/);await p.goto(BASE+'#desk');await demo(p,{role:'2'});await p.goto(BASE+'#reports');await p.locator('select[name="report-scope"]').selectOption('All JKs');assert.equal(await p.locator('.report-table tbody tr').count(),12);
});
await run('5. Public/mobile routes, keyboard, invalid links, persistence and reset',async(p)=>{
 await p.keyboard.press('Tab');assert.match(await p.locator(':focus').innerText(),/Skip to content/);await login(p);await adult(p,'2145550101');const n=(await state(p)).registrations.length;await p.reload();assert.equal((await state(p)).registrations.length,n);await p.goto(BASE+'#event');await p.setViewportSize({width:390,height:844});await p.locator('iframe').scrollIntoViewIfNeeded();await p.waitForTimeout(1500);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('input[type="tel"]').count(),0);await p.screenshot({path:`evidence/${out}-event-mobile.png`,fullPage:true});await p.goto(BASE+'#ticket/invalid');assert.match(await p.locator('main').innerText(),/isn’t valid/);await p.goto(BASE+'#waiver/invalid');assert.match(await p.locator('main').innerText(),/isn’t valid/);await p.goto(BASE+'#desk');await p.setViewportSize({width:1440,height:1000});await click(p,'demo-controls');await click(p,'reset');assert.equal((await state(p)).registrations.length,24);await p.screenshot({path:`evidence/${out}-desk.png`,fullPage:true});
});
await browser.close();const result={date:new Date().toISOString(),browser:'Installed Google Chrome via Playwright',viewports:['1440x1000','390x844'],run:out,results,pageErrors:allErrors};fs.writeFileSync(`evidence/browser-${out}.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));process.exitCode=results.some(r=>r.status==='Fail')||allErrors.length?1:0;})();
